nelmio_api_doc:
    documentation:
        info:
            title: Hooly Foodtruck API
            description: API pour la gestion des réservations de foodtrucks
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)